### ISSUE TITLE
Compiler options

### ISSUE THREAD

**Issue by Nokitoo** [mage/mage-validator#4]
It should be specified that the compiler options experimentalDecorators and emitDecoratorMetadata have to be set to true otherwise it doesn't work.
Acl decorator should also check for Reflect.getMetadata return and throw an error if it's undefined (meaning that emitDecoratorMetadata flag has not been set).

**Comment by stelcheck** [comment]
> It should be specified that the compiler options experimentalDecorators and emitDecoratorMetadata have to be set to true otherwise it doesn't work.

It already is, under https://github.com/mage/mage-validator#installation

> Acl decorator should also check for Reflect.getMetadata return and throw an error if it's undefined (meaning that emitDecoratorMetadata flag has not been set).

Agreed. I believe https://github.com/mage/mage-validator/pull/5 solves this issue.

Closing, since there are no actionable left. Please reopen if I missed something.
